Email automation for App installed and App Uninstalled
oscdev/fbt-bundle pull request #119
Opened 2024-12-19 12:33 UTC by Guddi1387

Email automation for App installed and App Uninstalled

2024-12-21 08:52 UTC, prafulG requested changes

2024-12-21 08:52 UTC, prafulG commented on cnf.js
> +export const cnf = {
Why confidential details pushed on git hub ?

2024-12-21 09:54 UTC, prafulG requested changes

2024-12-21 09:54 UTC, prafulG commented on .env
>  SHOPIFY_API_KEY=3d1a2c1b4bfc22486552326ce0932459
Keep .env in ignore

2024-12-21 10:21 UTC, prafulG requested changes

2024-12-21 10:21 UTC, prafulG commented on app/shopify.server.ts
> +      await appInstallation.getshop(admin);
Why this we need ?

2024-12-21 11:17 UTC, prafulG commented
Configure lint, prettier, husky and provide me coverage report first.

2024-12-21 11:20 UTC, Guddi1387 commented
> Configure lint, prettier, husky and provide me coverage report first.

Yes, sir, we will follow up.

2025-01-18 05:23 UTC, Guddi1387 commented on .env
>  SHOPIFY_API_KEY=3d1a2c1b4bfc22486552326ce0932459
sir .env is already in git ignore.

2025-01-18 05:24 UTC, Guddi1387 commented on app/shopify.server.ts
> +      await appInstallation.getshop(admin);
yes we have correct this

2025-01-18 08:54 UTC, merged